### ISSUE TITLE
exitButton covers startButton

### ISSUE THREAD

**Issue by Sammylandler** [Sammylandler/qhamexam#1]
Inside the mainLayout, there is a buttonLayout which contains the startButton and exitButton. The exitButton is added after the startButton, so only the exitButton is shown.

![Here is what it looks like](https://user-images.githubusercontent.com/19352597/40591954-d9e2b766-61de-11e8-96f8-c38cc5c43f0a.png)

**Comment by macetw** [comment]
I see you gave each A layout constructor call a pointer to "this." I think that's your problem. Unlike widgets and other qobjects, that should have a pointer to their parent, qlayouts should NOT. Their parent relationship is determined later, by calls of "setLayout()" by a widget or "addLayout()" by a higher level layout.

Did that make sense?

Good work, Sam!

Dad

**Comment by macetw** [comment]
So I'm talking about what is currently on lines 17 and 18.

**Comment by macetw** [comment]
Aha. I forgot this about qmainwindow.

You don't really want to use a main window until you have a menu bar, or a tool bar, or a status bar, or you have something dockable. For now, you have none of that. Use qwindow or just a plain qwidget maybe.

If you still want to use qmainwindow, is that you first need to put all the widgets inside what's called a "central widget" and set the central widget to be that widget (and layout) everything is in. That's a bunch of more complicated work.

**Comment by macetw** [comment]
It's best practice to check the documentation for an example, and to try and understand each line of it.

**Comment by macetw** [comment]
I love you!

-Dad

**Comment by macetw** [comment]
SUCCESS! It looks good, Sam!
