### ISSUE TITLE
How to open examwindow on the push of a QPushButton

### ISSUE THREAD

**Issue by Sammylandler** [Sammylandler/qhamexam#2]
How to you open a new QWidget class on QPushButton click. 

I think that it will look something like this:

connect(button, SIGNAL(clicked()), widget, SLOT(show()))

When I tried that, I got compilation errors:

"no matching function for call to 'MainWindow::connect(QPushButton*&, const char*, ExamWindow&, const char*)''"

**Comment by Sammylandler** [comment]
I want to open the examination window on the push of the startButton. I also want to pass information to that class on the type of examination. Here is what I have so far:

![so far](https://user-images.githubusercontent.com/19352597/40691298-e22420a2-6370-11e8-93e0-63aecec0225a.png)

**Comment by macetw** [comment]
it looks good, Sam!

My approach would be to create my own slot function, a member function of
the main window class. In that slot, you would create the new QWindow. (Are
you using QWindow? I think you should). When you create it, you would run
show() and open(), I think.

Your .h file might look a little like this, assuming the window is called
SamsTitleWindow...


class SamsTitleWindow : public QWindow {
    Q_OBJECT
  public:
   SamsTitleWindow(QObject * parent = 0);
    ~SamsTitleWindow() {};

    otherPublicFunctionsIfYouHaveAny();

  public slots:
    openExam();
    otherSlotFunctionsIfYouHaveAny();

}

**Comment by macetw** [comment]
I just refused your call, because I'm still at work, but I was already
answering your question. I need you to work by yourself with what I'm
offering above.

**Comment by Sammylandler** [comment]
I am currently having trouble converting a QWidget based class to a QWindow based class.

![more trouble](https://user-images.githubusercontent.com/19352597/40694176-f46976f8-6380-11e8-8f9a-762c4e94af2e.png)

**Comment by macetw** [comment]
I think you want QDialog rather than qwindow. Sorry.

**Comment by Sammylandler** [comment]
I am having a hard time finding the correct way to make an exam app.

Here is my idea (each point has its own class):
- A MainWindow to choose type of exam
- A ExamWindow with radio buttons for multiple choice selection
- A Exam class for future exam functionality (random question picker)
- A ExamResults window that collects and displays exam results.

I don't know if this is a good way to go about this, but I have some of this completed (and it compiles as well).

**Comment by Sammylandler** [comment]
By the way, I created a branch and pushed changes: "exam-dev"

**Comment by macetw** [comment]
Sounds like you are making a "design spec." :)

Good work.

Now remember, you can't do it all at one time. I suggest you break down the
work in little bits of functionality so that you can deliver small pieces
as "complete" but not other pieces that are half-complete.

**Comment by Sammylandler** [comment]
I am trying to connect the signal "clicked" to the slot in exam "startExam"
Here is the code:

``
Exam exam;
``
``
connect(startButton, SIGNAL(clicked()), exam, SLOT(startExam()));
``

However, I get compilation errors:

``(/home/sam/projects/qhamexam/mainwindow.cpp:55: error: no matching function for call to ‘MainWindow::connect(QPushButton*&, const char*, Exam&, const char*)’
 connect(startButton, SIGNAL(clicked()), exam, SLOT(startExam()));
``

**Comment by macetw** [comment]
If Exam is a type of widget or dialog, you need to say it differently,
using pointers.

Exam *exam = new Exam( this )

You can see in documentation that the QObject::connect() function relies on
QObject-based pointers to be passed in, but you weren't passing in
pointers. You were passing in the whole object.

**Comment by Sammylandler** [comment]
I fixed that compilation problem, Thank You!

**Comment by Sammylandler** [comment]
But now, there is a bug. The window will not open on startButton click. I have pushed a commit.

**Comment by macetw** [comment]
I think you need to independently call the show function on the Q dialog.

**Comment by Sammylandler** [comment]
Thank you! That solved the problem.
